(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();document.addEventListener("DOMContentLoaded",function(){const u=document.querySelector(".burger-menu"),l=document.querySelector(".nav"),i=document.querySelector(".modal"),a=document.querySelector(".modal-close");u.addEventListener("click",function(){l.classList.toggle("nav-active")}),a.addEventListener("click",function(){i.style.display="none"}),window.addEventListener("click",function(e){e.target===i&&(i.style.display="none")}),window.addEventListener("keydown",function(e){e.key==="Escape"&&(i.style.display="none")});const t=document.querySelector(".load-more");let r=1;t.addEventListener("click",function(){r++,c(r)});function c(e){fetch(`https://portfolio-js.b.goit.study/api/projects?page=${e}`).then(o=>o.json()).then(o=>{p(o.projects),o.hasMore||(t.style.display="none")}).catch(o=>console.error("Error:",o))}function p(e){const o=document.querySelector(".project-list");e.forEach(n=>{const s=document.createElement("li");s.innerHTML=`
        <img src="${n.image}" alt="${n.title}">
        <div class="project-info">
          <h3>${n.title}</h3>
          <p>${n.description}</p>
          <a href="${n.link}" target="_blank">View Project</a>
        </div>
      `,o.appendChild(s)})}c(r),document.querySelectorAll(".faq-question").forEach(e=>{e.addEventListener("click",function(){const o=this.nextElementSibling;o.style.display==="block"?o.style.display="none":(document.querySelectorAll(".faq-answer").forEach(n=>n.style.display="none"),o.style.display="block")})}),f();function f(){fetch("https://portfolio-js.b.goit.study/api/reviews").then(e=>e.json()).then(e=>{y(e.reviews),m()}).catch(e=>{console.error("Error:",e),document.querySelector(".reviews-slider").innerHTML="<p>Not found</p>"})}function y(e){const o=document.querySelector(".swiper-wrapper");e.forEach(n=>{const s=document.createElement("div");s.className="swiper-slide",s.innerHTML=`
        <p>${n.text}</p>
        <p><strong>- ${n.author}</strong></p>
      `,o.appendChild(s)})}function m(){new Swiper(".swiper-container",{loop:!0,pagination:{el:".swiper-pagination",clickable:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"}})}const d=document.getElementById("contact-form");d.addEventListener("submit",function(e){e.preventDefault();const o=new FormData(d);fetch("https://portfolio-js.b.goit.study/api/contact",{method:"POST",body:o}).then(n=>n.json()).then(n=>{n.success?(alert("Thank you for your interest in cooperation!"),d.reset()):alert("An error occurred. Please try again.")}).catch(n=>{console.error("Error:",n),alert("An error occurred. Please try again.")})})});
//# sourceMappingURL=commonHelpers.js.map
